overrides: bear-requirements.yaml

name: coala-bears
description: "Bears for coala (Code Analysis Application)"
build_version: 0.12.0.dev99999999999999
current_version: 0.12.0.dev
version: 0.12.0.dev
release: 0.12.0.dev
test_pyversion: 3.4
branch: master
package_module: bears
docs_output_dir: docs/API
entry_points:
  coalabears:
    - coala_official_bears = bears

configuration:
  template_dir:
    - .moban.dt/
    - .ci/
    - ../coala-mobans/templates/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - setup.py: bears-setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: test-requirements.txt.jj2
  - bears/VERSION: VERSION.jj2
  - Gemfile: Gemfile.jj2
  - package.json: package.json.jj2
  - bear-requirements.txt: bear-requirements.txt.jj2
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/run_with_env.cmd: run_with_env.cmd
