overrides: bear-requirements.yaml

allow_generic_no_cover: true

nocover_file_globs:
  - .ci/*

nocover_regexes:
  - '# backwards compatible no results'
  # Allows retaining existing indentation
  - 'if True:'
